version: '3.8'

services:
  nginx:
    image: library/nginx:latest
    restart: always
    volumes:
      - ./.docker/staging/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/repo
    networks:
      - default
      - template-repo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.from-home-template-repo.rule=Host(`template-repo-stage.from-home.de`)"
      - "traefik.http.routers.from-home-template-repo.tls=true"
      - "traefik.http.routers.from-home-cdn.tls.certresolver=fromHome"

networks:
  default:
    external:
      name: gateway
  template-repo: