version: '3.8'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: ./.docker/development/php
    restart: "no"
    volumes:
      - ./:/repo
    working_dir: /repo
    networks:
      - pdf-label
    tty: true
    environment:
      XDEBUG_MODE: "develop,coverage"

  phive:
    image: hyperized/phive:latest
    restart: 'no'
    volumes:
      - ./:/repo
      - phive:/root/.phive
    working_dir: /repo
    networks:
      - pdf-label

networks:
  pdf-label:

volumes:
  phive: